# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'CurrencyExchanger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxAlamofire', '~> 5.1'
  pod 'RxSwift', '~> 5.1'
  pod 'RxCocoa', '~> 5.1'

  # Pods for CurrencyExchanger

  target 'CurrencyExchangerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CurrencyExchangerUITests' do
    # Pods for testing
  end

end
